# Generated by Django 4.2.1 on 2024-10-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='staffmember',
            new_name='staff_member',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vk_url', models.URLField(blank=True, null=True)),
                ('vk_id', models.CharField(max_length=255, unique=True)),
                ('hh_url', models.URLField(blank=True, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='srch.profession')),
            ],
        ),
    ]
