# Generated by Django 4.2.1 on 2024-10-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srch', '0002_profession_rename_staffmember_tasks_staff_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked',
        ),
    ]
